baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "ru"
title = "DrochiczynPoleski"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
name = "Tymoteusz Kaljuta"

[params]
author = "Tymoteusz Kaljuta"
description = "Anubis is a simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional
  
[[params.social]]
id = "docs"
url = "https://gohugo.io/documentation/"

[[params.social]]
id = "github"
url = "https://github.com/mitrichius/hugo-theme-anubis"

[languages.en]
languageName = "English"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[languages.ru]
languageName = "Russian"

[[languages.ru.menu.main]]
identifier = "about.ru"
name = "О Авторе"
url = "/about.ru/"
weight = 1

[[languages.ru.menu.main]]
identifier = "tags"
name = "Теги"
url = "/tags/"
weight = 2

[[languages.ru.menu.main]]
identifier = "archive"
name = "Архив"
url = "/posts/"
weight = 3

[[languages.ru.params]]
locale = "ru-ru"

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true